[package]
name = "wing_generate"
version = "0.0.1"
authors = ["EthanJustice <47954690+EthanJustice@users.noreply.github.com>"]
edition = "2018"

[dependencies]
clap = "~2.33.2"
serde = { version = "~1.0.115", features = ["derive"] }
serde_json = "~1.0.57"